///REGISTER USER
export const SIGNUP_NEW_USER = "SIGNUP_NEW_USER";

// AUTH Constants
export const FETCH_TOKEN = "FETCH_TOKEN";
export const FETCH_TOKEN_FAILED = "FETCH_TOKEN_FAILED";
export const TOKEN_REMOVE = "TOKEN_REMOVE";

//USERS CONSTANTS
export const TOGGLE_ACTIVITY = "TOGGLE_ACTIVITY";
export const GET_USERS = "GET_USERS";
export const GET_USERSDATES = "GET_USERSDATES";
export const GET_USER = "GET_USER"
export const GET_USERLINKS = "GET_USERLINKS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_LINK = "DELETE_LINK";
export const CHANGE_ROLE = "CHANGE_ROLE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

//CATEGORIES CONSTANTS
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

//REPORTS CONSTANTS
export const GET_REPORTS = "GET_REPORTS";
export const ADD_REPORT = "ADD_REPORT";
export const DELETE_REPORT = "DELETE_REPORT";

//PICTURES CONSTANTS
export const ADD_PICTURE = "ADD_PICTURE";

//ITEMS CONSTANTS
export const GET_ITEMS = "GET_ITEMS";
export const GET_ITEM = "GET_ITEM";
export const GET_ITEMS_BY_USERID = "GET_ITEMS_BY_USERID";
export const GET_ITEMS_BY_CATEGORYID = "GET_ITEMS_BY_CATEGORYID";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const DELETE_ITEMS_BYUSER = "DELETE_ITEMS_BYUSER";

//ADMINS CONSTANTS
export const GET_ADMINS = "GET_ADMINS";
export const CREATE_ADMIN = "CREATE_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
//export const CHANGE_ROLE = "CHANGE_ROLE";

// App Notification
export const TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION";
export const TOGGLE_NOTIFICATION_OFF = "TOGGLE_NOTIFICATION_OFF";
